/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    posts: Post;
    media: Media;
    faq: Faq;
    services: Service;
    subservices: Subservice;
    cases: Case;
    caseGroups: CaseGroup;
    logos: Logo;
    logoGroups: LogoGroup;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    logos: {
      groups: 'logoGroups';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    subservices: SubservicesSelect<false> | SubservicesSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    caseGroups: CaseGroupsSelect<false> | CaseGroupsSelect<true>;
    logos: LogosSelect<false> | LogosSelect<true>;
    logoGroups: LogoGroupsSelect<false> | LogoGroupsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es' | 'pt-br') | ('en' | 'es' | 'pt-br')[];
  globals: {
    menu: Menu;
    homepage: Homepage;
    social: Social;
    privacyPolicy: PrivacyPolicy;
  };
  globalsSelect: {
    menu: MenuSelect<false> | MenuSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    social: SocialSelect<false> | SocialSelect<true>;
    privacyPolicy: PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
  };
  locale: 'en' | 'es' | 'pt-br';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  slug?: string | null;
  relPermalink: string;
  title: string;
  excerpt: string;
  image?: (number | null) | Media;
  publishedDate: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta: {
    title: string;
    description: string;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  blurhash?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  slug?: string | null;
  relPermalink: string;
  name: string;
  /**
   * Use uma imagem de 2560x560px no formato AVIF. Para redimensionar e otimizar, utilize o Squoosh (https://squoosh.app/).
   */
  image?: (number | null) | Media;
  hero: {
    /**
     * Para configurar o título, utilize [[left:normal:TEXTO]], [[left:bold:TEXTO]], [[right:normal:TEXTO]] ou [[right:bold:TEXTO]], substituindo TEXTO pelo conteúdo desejado e definindo o peso da fonte como normal ou bold.
     */
    title: string;
  };
  sections: (
    | TitleWithContent
    | CasesSlide
    | ServicesArchive
    | SubservicesArchive
    | SubservicesMarquee
    | LogosMarquee
    | CardsGrid
    | TitleWithAccordions
    | FeaturedImages
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleWithContent".
 */
export interface TitleWithContent {
  /**
   * Para configurar o título, utilize [[left:normal:TEXTO]], [[left:bold:TEXTO]], [[right:normal:TEXTO]] ou [[right:bold:TEXTO]], substituindo TEXTO pelo conteúdo desejado e definindo o peso da fonte como normal ou bold.
   */
  title?: string | null;
  /**
   * Define o tamanho da fonte do título.
   */
  titleSize?: ('sm' | 'lg') | null;
  /**
   * Define a largura do container do título.
   */
  titleWidthSize?: ('xl' | 'lg' | 'md' | 'sm' | 'xs') | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  circleText?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TitleWithContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesSlide".
 */
export interface CasesSlide {
  /**
   * Este título não é exibido visualmente, mas é utilizado para acessibilidade e estrutura semântica.
   */
  title: string;
  relatedCaseGroups: (number | CaseGroup)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'CasesSlide';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseGroups".
 */
export interface CaseGroup {
  id: number;
  title: string;
  logos: (number | Case)[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  slug?: string | null;
  relPermalink: string;
  relatedGroups: (number | CaseGroup)[];
  title: string;
  color: string;
  theme: 'light' | 'dark';
  image?: (number | null) | Media;
  companyName: string;
  companyLogo: number | Logo;
  year: number;
  team: string;
  sections: (
    | TitleWithContent
    | CasesSlide
    | ServicesArchive
    | SubservicesArchive
    | SubservicesMarquee
    | LogosMarquee
    | CardsGrid
    | TitleWithAccordions
    | FeaturedImages
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos".
 */
export interface Logo {
  id: number;
  title: string;
  image?: (number | null) | Media;
  groups?: {
    docs?: (number | LogoGroup)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logoGroups".
 */
export interface LogoGroup {
  id: number;
  title: string;
  logos: (number | Logo)[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesArchive".
 */
export interface ServicesArchive {
  /**
   * Para configurar o título, utilize [[left:normal:TEXTO]], [[left:bold:TEXTO]], [[right:normal:TEXTO]] ou [[right:bold:TEXTO]], substituindo TEXTO pelo conteúdo desejado e definindo o peso da fonte como normal ou bold.
   */
  title: string;
  /**
   * Define o tamanho da fonte do título.
   */
  titleSize?: ('sm' | 'lg') | null;
  /**
   * Define a largura do container do título.
   */
  titleWidthSize?: ('xl' | 'lg' | 'md' | 'sm' | 'xs') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ServicesArchive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SubservicesArchive".
 */
export interface SubservicesArchive {
  /**
   * Para configurar o título, utilize [[left:normal:TEXTO]], [[left:bold:TEXTO]], [[right:normal:TEXTO]] ou [[right:bold:TEXTO]], substituindo TEXTO pelo conteúdo desejado e definindo o peso da fonte como normal ou bold.
   */
  title: string;
  /**
   * Define o tamanho da fonte do título.
   */
  titleSize?: ('sm' | 'lg') | null;
  /**
   * Define a largura do container do título.
   */
  titleWidthSize?: ('xl' | 'lg' | 'md' | 'sm' | 'xs') | null;
  relatedServices?: (number | Service)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'SubservicesArchive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SubservicesMarquee".
 */
export interface SubservicesMarquee {
  internalBlockName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'SubservicesMarquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosMarquee".
 */
export interface LogosMarquee {
  /**
   * Use **texto** para deixar partes do texto em negrito. Exemplo: A Jogajunto é a **melhor** empresa.
   */
  title: string;
  /**
   * Selecione uma ou mais coleções de logos para exibir no componente Marquee.
   */
  relatedLogoGroups: (number | LogoGroup)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'LogosMarquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsGrid".
 */
export interface CardsGrid {
  title: string;
  list?:
    | {
        title?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        source?: {
          name?: string | null;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'CardsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleWithAccordions".
 */
export interface TitleWithAccordions {
  /**
   * Use **texto** para deixar partes do texto em negrito. Exemplo: A Jogajunto é a **melhor** empresa.
   */
  title: string;
  list?:
    | {
        title?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TitleWithAccordions';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedImages".
 */
export interface FeaturedImages {
  internalBlockName?: string | null;
  lightColor?: string | null;
  darkColor?: string | null;
  list: {
    image: number | Media;
    width: 'full' | 'half';
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'FeaturedImages';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subservices".
 */
export interface Subservice {
  id: number;
  slug?: string | null;
  relPermalink: string;
  service: number | Service;
  title: string;
  description: string;
  hero?: {
    title?: string | null;
    description?: string | null;
  };
  sections: (
    | TitleWithContent
    | CasesSlide
    | ServicesArchive
    | SubservicesArchive
    | SubservicesMarquee
    | LogosMarquee
    | CardsGrid
    | TitleWithAccordions
    | FeaturedImages
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'subservices';
        value: number | Subservice;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'caseGroups';
        value: number | CaseGroup;
      } | null)
    | ({
        relationTo: 'logos';
        value: number | Logo;
      } | null)
    | ({
        relationTo: 'logoGroups';
        value: number | LogoGroup;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  slug?: T;
  relPermalink?: T;
  title?: T;
  excerpt?: T;
  image?: T;
  publishedDate?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurhash?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  relPermalink?: T;
  name?: T;
  image?: T;
  hero?:
    | T
    | {
        title?: T;
      };
  sections?:
    | T
    | {
        TitleWithContent?: T | TitleWithContentSelect<T>;
        CasesSlide?: T | CasesSlideSelect<T>;
        ServicesArchive?: T | ServicesArchiveSelect<T>;
        SubservicesArchive?: T | SubservicesArchiveSelect<T>;
        SubservicesMarquee?: T | SubservicesMarqueeSelect<T>;
        LogosMarquee?: T | LogosMarqueeSelect<T>;
        CardsGrid?: T | CardsGridSelect<T>;
        TitleWithAccordions?: T | TitleWithAccordionsSelect<T>;
        FeaturedImages?: T | FeaturedImagesSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleWithContent_select".
 */
export interface TitleWithContentSelect<T extends boolean = true> {
  title?: T;
  titleSize?: T;
  titleWidthSize?: T;
  content?: T;
  circleText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CasesSlide_select".
 */
export interface CasesSlideSelect<T extends boolean = true> {
  title?: T;
  relatedCaseGroups?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesArchive_select".
 */
export interface ServicesArchiveSelect<T extends boolean = true> {
  title?: T;
  titleSize?: T;
  titleWidthSize?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SubservicesArchive_select".
 */
export interface SubservicesArchiveSelect<T extends boolean = true> {
  title?: T;
  titleSize?: T;
  titleWidthSize?: T;
  relatedServices?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SubservicesMarquee_select".
 */
export interface SubservicesMarqueeSelect<T extends boolean = true> {
  internalBlockName?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosMarquee_select".
 */
export interface LogosMarqueeSelect<T extends boolean = true> {
  title?: T;
  relatedLogoGroups?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsGrid_select".
 */
export interface CardsGridSelect<T extends boolean = true> {
  title?: T;
  list?:
    | T
    | {
        title?: T;
        content?: T;
        source?:
          | T
          | {
              name?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TitleWithAccordions_select".
 */
export interface TitleWithAccordionsSelect<T extends boolean = true> {
  title?: T;
  list?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedImages_select".
 */
export interface FeaturedImagesSelect<T extends boolean = true> {
  internalBlockName?: T;
  lightColor?: T;
  darkColor?: T;
  list?:
    | T
    | {
        image?: T;
        width?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subservices_select".
 */
export interface SubservicesSelect<T extends boolean = true> {
  slug?: T;
  relPermalink?: T;
  service?: T;
  title?: T;
  description?: T;
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  sections?:
    | T
    | {
        TitleWithContent?: T | TitleWithContentSelect<T>;
        CasesSlide?: T | CasesSlideSelect<T>;
        ServicesArchive?: T | ServicesArchiveSelect<T>;
        SubservicesArchive?: T | SubservicesArchiveSelect<T>;
        SubservicesMarquee?: T | SubservicesMarqueeSelect<T>;
        LogosMarquee?: T | LogosMarqueeSelect<T>;
        CardsGrid?: T | CardsGridSelect<T>;
        TitleWithAccordions?: T | TitleWithAccordionsSelect<T>;
        FeaturedImages?: T | FeaturedImagesSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  slug?: T;
  relPermalink?: T;
  relatedGroups?: T;
  title?: T;
  color?: T;
  theme?: T;
  image?: T;
  companyName?: T;
  companyLogo?: T;
  year?: T;
  team?: T;
  sections?:
    | T
    | {
        TitleWithContent?: T | TitleWithContentSelect<T>;
        CasesSlide?: T | CasesSlideSelect<T>;
        ServicesArchive?: T | ServicesArchiveSelect<T>;
        SubservicesArchive?: T | SubservicesArchiveSelect<T>;
        SubservicesMarquee?: T | SubservicesMarqueeSelect<T>;
        LogosMarquee?: T | LogosMarqueeSelect<T>;
        CardsGrid?: T | CardsGridSelect<T>;
        TitleWithAccordions?: T | TitleWithAccordionsSelect<T>;
        FeaturedImages?: T | FeaturedImagesSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseGroups_select".
 */
export interface CaseGroupsSelect<T extends boolean = true> {
  title?: T;
  logos?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos_select".
 */
export interface LogosSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  groups?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logoGroups_select".
 */
export interface LogoGroupsSelect<T extends boolean = true> {
  title?: T;
  logos?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: number;
  menu: {
    type?: ('link' | 'submenu') | null;
    label?: string | null;
    link?: string | null;
    submenu?:
      | {
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  relPermalink: string;
  sections: (
    | TitleWithContent
    | CasesSlide
    | ServicesArchive
    | SubservicesArchive
    | SubservicesMarquee
    | LogosMarquee
    | CardsGrid
    | TitleWithAccordions
    | FeaturedImages
  )[];
  meta: {
    title: string;
    description: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social".
 */
export interface Social {
  id: number;
  instagram: {
    title: string;
    url?: string | null;
  };
  facebook: {
    title: string;
    url?: string | null;
  };
  whatsapp: {
    title: string;
    url?: string | null;
  };
  youtube: {
    title: string;
    url?: string | null;
  };
  linkedin: {
    title: string;
    url?: string | null;
  };
  threads: {
    title: string;
    url?: string | null;
  };
  tiktok: {
    title: string;
    url?: string | null;
  };
  x: {
    title: string;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacyPolicy".
 */
export interface PrivacyPolicy {
  id: number;
  title: string;
  description: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta: {
    title: string;
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  menu?:
    | T
    | {
        type?: T;
        label?: T;
        link?: T;
        submenu?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  relPermalink?: T;
  sections?:
    | T
    | {
        TitleWithContent?: T | TitleWithContentSelect<T>;
        CasesSlide?: T | CasesSlideSelect<T>;
        ServicesArchive?: T | ServicesArchiveSelect<T>;
        SubservicesArchive?: T | SubservicesArchiveSelect<T>;
        SubservicesMarquee?: T | SubservicesMarqueeSelect<T>;
        LogosMarquee?: T | LogosMarqueeSelect<T>;
        CardsGrid?: T | CardsGridSelect<T>;
        TitleWithAccordions?: T | TitleWithAccordionsSelect<T>;
        FeaturedImages?: T | FeaturedImagesSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social_select".
 */
export interface SocialSelect<T extends boolean = true> {
  instagram?:
    | T
    | {
        title?: T;
        url?: T;
      };
  facebook?:
    | T
    | {
        title?: T;
        url?: T;
      };
  whatsapp?:
    | T
    | {
        title?: T;
        url?: T;
      };
  youtube?:
    | T
    | {
        title?: T;
        url?: T;
      };
  linkedin?:
    | T
    | {
        title?: T;
        url?: T;
      };
  threads?:
    | T
    | {
        title?: T;
        url?: T;
      };
  tiktok?:
    | T
    | {
        title?: T;
        url?: T;
      };
  x?:
    | T
    | {
        title?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacyPolicy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}